### ISSUE TITLE
Playlist index not working on v2.2.2

### ISSUE THREAD

**Issue by wierdopi** [jely2002/youtube-dl-gui#148]
Should probably mention #97 and #98

I tried this on both the windows installer version and the portable version, got the same result. I'm trying to automatically put each playlist in its own folder and number the files, which should be possible by setting the custom filename format: %(playlist_title)s/%(playlist_index)s-%(title)s.%(ext)s

Didn't work though, idk if this is just an issue with my computer

**To Reproduce**
1. Install, set download location
2. Set filename format to %(playlist_title)s/%(playlist_index)s-%(title)s.%(ext)s
3. Start downloading a playlist
4. The video files in the playlist will not be numbered, nor will they be in their own separate folder

**Additional info:**
 - Windows 10
 - v2.2.2 of the app
 - both portable and windows installer versions, I didn't try mac or linux
 - intel cpu

**Additional context**
Happened with mkv and mp4. My output settings were
Save metadata: true
Save thumbnail as file: false
Keep unmerged files: false

I also tried just %(playlist_index)s-%(title)s.%(ext)s for the filename format, and it didn't make any difference. Also tried %(playlist_title)s/%(playlist_index)s-%(title).200s.%(ext)s and it was the same. I tried this whole thing on a different computer as well, also running windows 10 with an intel cpu, same thing happened

**Comment by jely2002** [comment]
Thanks for your report! I have applied a fix, it will be released in v2.3.1.

**Comment by wierdopi** [comment]
Fantastic, thank you!

**Comment by brucefu225** [comment]
This issue happen again with v2.4.0 installed and portable.
I tried this on both version with v.2.4.0 in windows 10 .
%(playlist_title)s/%(playlist_index)s-%(title)s.%(ext)s for the filename format, also tried %(uploader)s/%(playlist)s/%(playlist_index)s-%(title)s-%(resolution)s , the result was the same.

**Comment by L0Lock** [comment]
Same here! It works fine using the terminal:

```bash
youtube-dl -i -f mp4 --yes-playlist https://www.youtube.com/playlist?list=PLa1F2ddGya_8acrgoQr1fTeIuQtkSd6BW --embed-thumbnail -o "C:\Users\Roikku\Downloads\%(playlist_index)02d - %(title).200s-(%(height)sp%(fps).0d).%(ext)s"
```

But OVD 2.4.0 ignores the `%(playlist_index)02d` part.

Thinking about it, it could be convenient to have some form of isolated output specifically for playlist. Maybe an option to output in a subfolder with the playlist's name or something.

<details>

<summary>Here's the log for one of the files:</summary>

```python
[youtube] uBDc0Eq70kM: Downloading webpage

[youtube] uBDc0Eq70kM: Downloading android player API JSON

[youtube] uBDc0Eq70kM: Downloading player dfd2e197

WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats

n = fMQL4rRWcgSBjefcb1n2 ; player = https://www.youtube.com/s/player/dfd2e197/player_ias.vflset/en_US/base.js

uBDc0Eq70kM: Traceback (most recent call last):

File "yt_dlp\extractor\youtube.py", line 2415, in _decrypt_nsig

File "yt_dlp\extractor\youtube.py", line 2441, in _extract_n_function

File "yt_dlp\extractor\youtube.py", line 2424, in _extract_n_function_name

File "yt_dlp\extractor\common.py", line 1186, in _search_regex

yt_dlp.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U

(caused by RegexNotFoundError('Unable to extract Initial JS player n function name; please report this issue on https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U')); please report this issue on https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U

[info] uBDc0Eq70kM: Downloading 1 format(s): 299+251

[info] Downloading video thumbnail 41 ...

[info] Writing video thumbnail 41 to: C:\Users\Roikku\Downloads\ - The Roast of Nature Clicker _ Scripting for Artists [14]-(1080p60).webp

[download] Destination: C:\Users\Roikku\Downloads\ - The Roast of Nature Clicker _ Scripting for Artists [14]-(1080p60).f299.mp4

[download] 0.0% of 101.14MiB at 100.34KiB/s ETA 17:12

[download] 0.0% of 101.14MiB at 301.01KiB/s ETA 05:44

[download] 0.0% of 101.14MiB at 638.50KiB/s ETA 02:42

[download] 0.0% of 101.14MiB at 1.34MiB/s ETA 01:15

[download] 0.0% of 101.14MiB at 634.71KiB/s ETA 02:43

[download] 0.1% of 101.14MiB at 743.64KiB/s ETA 02:19

[download] 0.1% of 101.14MiB at 1.00MiB/s ETA 01:40

[download] 0.2% of 101.14MiB at 1.63MiB/s ETA 01:01

[download] 0.5% of 101.14MiB at 2.59MiB/s ETA 00:38

[download] 1.0% of 101.14MiB at 4.34MiB/s ETA 00:23

[download] 2.0% of 101.14MiB at 7.43MiB/s ETA 00:13

[download] 4.0% of 101.14MiB at 12.63MiB/s ETA 00:07

[download] 7.9% of 101.14MiB at 12.04MiB/s ETA 00:07

[download] 9.5% of 101.14MiB at 11.86MiB/s ETA 00:07

[download] 9.5% of 101.14MiB at 9.74KiB/s ETA 02:40:20

[download] 9.5% of 101.14MiB at 29.22KiB/s ETA 53:26

[download] 9.5% of 101.14MiB at 67.53KiB/s ETA 23:07

[download] 9.5% of 101.14MiB at 144.71KiB/s ETA 10:47

[download] 9.5% of 101.14MiB at 214.51KiB/s ETA 07:16

[download] 9.6% of 101.14MiB at 432.95KiB/s ETA 03:36

[download] 9.6% of 101.14MiB at 758.48KiB/s ETA 02:03

[download] 9.8% of 101.14MiB at 1.33MiB/s ETA 01:08

[download] 10.0% of 101.14MiB at 2.43MiB/s ETA 00:37

[download] 10.5% of 101.14MiB at 4.19MiB/s ETA 00:21

[download] 11.5% of 101.14MiB at 6.64MiB/s ETA 00:13

[download] 13.5% of 101.14MiB at 10.07MiB/s ETA 00:08

[download] 17.4% of 101.14MiB at 12.14MiB/s ETA 00:06

[download] 19.2% of 101.14MiB at 11.46MiB/s ETA 00:07

[download] 19.2% of 101.14MiB at 91.21KiB/s ETA 15:17

[download] 19.2% of 101.14MiB at 273.63KiB/s ETA 05:05

[download] 19.2% of 101.14MiB at 585.27KiB/s ETA 02:23

[download] 19.2% of 101.14MiB at 1.22MiB/s ETA 01:06

[download] 19.2% of 101.14MiB at 292.45KiB/s ETA 04:46

[download] 19.2% of 101.14MiB at 401.21KiB/s ETA 03:28

[download] 19.3% of 101.14MiB at 803.69KiB/s ETA 01:44

[download] 19.4% of 101.14MiB at 1.39MiB/s ETA 00:58

[download] 19.6% of 101.14MiB at 2.01MiB/s ETA 00:40

[download] 20.1% of 101.14MiB at 3.29MiB/s ETA 00:24

[download] 21.1% of 101.14MiB at 4.74MiB/s ETA 00:16

[download] 23.1% of 101.14MiB at 8.26MiB/s ETA 00:09

[download] 27.1% of 101.14MiB at 12.48MiB/s ETA 00:05

[download] 28.7% of 101.14MiB at 10.17MiB/s ETA 00:07

[download] 28.7% of 101.14MiB at 77.18KiB/s ETA 15:57

[download] 28.7% of 101.14MiB at 215.01KiB/s ETA 05:43

[download] 28.7% of 101.14MiB at 501.69KiB/s ETA 02:27

[download] 28.7% of 101.14MiB at 1.05MiB/s ETA 01:08

[download] 28.7% of 101.14MiB at 426.12KiB/s ETA 02:53

[download] 28.7% of 101.14MiB at 748.81KiB/s ETA 01:38

[download] 28.8% of 101.14MiB at 921.57KiB/s ETA 01:20

[download] 28.9% of 101.14MiB at 1.36MiB/s ETA 00:53

[download] 29.2% of 101.14MiB at 2.02MiB/s ETA 00:35

[download] 29.6% of 101.14MiB at 3.49MiB/s ETA 00:20

[download] 30.6% of 101.14MiB at 6.38MiB/s ETA 00:11

[download] 32.6% of 101.14MiB at 10.73MiB/s ETA 00:06

[download] 36.6% of 101.14MiB at 16.29MiB/s ETA 00:03

[download] 38.3% of 101.14MiB at 19.25MiB/s ETA 00:03

[download] 38.3% of 101.14MiB at 91.21KiB/s ETA 11:41

[download] 38.3% of 101.14MiB at 273.64KiB/s ETA 03:53

[download] 38.3% of 101.14MiB at 638.50KiB/s ETA 01:40

[download] 38.3% of 101.14MiB at 1.34MiB/s ETA 00:46

[download] 38.3% of 101.14MiB at 676.18KiB/s ETA 01:34

[download] 38.3% of 101.14MiB at 660.64KiB/s ETA 01:36

[download] 38.4% of 101.14MiB at 928.80KiB/s ETA 01:08

[download] 38.5% of 101.14MiB at 1.57MiB/s ETA 00:39

[download] 38.7% of 101.14MiB at 2.38MiB/s ETA 00:26

[download] 39.2% of 101.14MiB at 2.86MiB/s ETA 00:21

[download] 40.2% of 101.14MiB at 4.90MiB/s ETA 00:12

[download] 42.2% of 101.14MiB at 8.75MiB/s ETA 00:06

[download] 46.2% of 101.14MiB at 13.98MiB/s ETA 00:03

[download] 48.0% of 101.14MiB at 16.44MiB/s ETA 00:03

[download] 48.0% of 101.14MiB at 83.61KiB/s ETA 10:43

[download] 48.1% of 101.14MiB at 250.84KiB/s ETA 03:34

[download] 48.1% of 101.14MiB at 540.28KiB/s ETA 01:39

[download] 48.1% of 101.14MiB at 1.13MiB/s ETA 00:46

[download] 48.1% of 101.14MiB at 415.75KiB/s ETA 02:09

[download] 48.1% of 101.14MiB at 419.87KiB/s ETA 02:07

[download] 48.2% of 101.14MiB at 649.58KiB/s ETA 01:22

[download] 48.3% of 101.14MiB at 1.07MiB/s ETA 00:48

[download] 48.5% of 101.14MiB at 1.65MiB/s ETA 00:31

[download] 49.0% of 101.14MiB at 3.08MiB/s ETA 00:16

[download] 50.0% of 101.14MiB at 4.93MiB/s ETA 00:10

[download] 52.0% of 101.14MiB at 8.59MiB/s ETA 00:05

[download] 56.0% of 101.14MiB at 8.53MiB/s ETA 00:05

[download] 57.8% of 101.14MiB at 9.56MiB/s ETA 00:04

[download] 57.8% of 101.14MiB at 12.32KiB/s ETA 59:04

[download] 57.8% of 101.14MiB at 36.96KiB/s ETA 19:41

[download] 57.8% of 101.14MiB at 86.24KiB/s ETA 08:26

[download] 57.8% of 101.14MiB at 182.56KiB/s ETA 03:59

[download] 57.9% of 101.14MiB at 377.30KiB/s ETA 01:55

[download] 57.9% of 101.14MiB at 622.70KiB/s ETA 01:10

[download] 58.0% of 101.14MiB at 977.21KiB/s ETA 00:44

[download] 58.1% of 101.14MiB at 1.37MiB/s ETA 00:31

[download] 58.3% of 101.14MiB at 2.32MiB/s ETA 00:18

[download] 58.8% of 101.14MiB at 3.25MiB/s ETA 00:12

[download] 59.8% of 101.14MiB at 5.75MiB/s ETA 00:07

[download] 61.8% of 101.14MiB at 9.84MiB/s ETA 00:03

[download] 65.7% of 101.14MiB at 13.50MiB/s ETA 00:02

[download] 67.7% of 101.14MiB at 15.49MiB/s ETA 00:02

[download] 67.7% of 101.14MiB at 200.67KiB/s ETA 02:46

[download] 67.7% of 101.14MiB at 602.00KiB/s ETA 00:55

[download] 67.7% of 101.14MiB at 1.37MiB/s ETA 00:23

[download] 67.7% of 101.14MiB at 2.45MiB/s ETA 00:13

[download] 67.7% of 101.14MiB at 576.36KiB/s ETA 00:57

[download] 67.8% of 101.14MiB at 782.73KiB/s ETA 00:42

[download] 67.8% of 101.14MiB at 1.09MiB/s ETA 00:29

[download] 68.0% of 101.14MiB at 1.37MiB/s ETA 00:23

[download] 68.2% of 101.14MiB at 1.98MiB/s ETA 00:16

[download] 68.7% of 101.14MiB at 3.25MiB/s ETA 00:09

[download] 69.7% of 101.14MiB at 5.46MiB/s ETA 00:05

[download] 71.7% of 101.14MiB at 8.87MiB/s ETA 00:03

[download] 75.6% of 101.14MiB at 13.79MiB/s ETA 00:01

[download] 77.4% of 101.14MiB at 16.29MiB/s ETA 00:01

[download] 77.4% of 101.14MiB at 23.34KiB/s ETA 16:43

[download] 77.4% of 101.14MiB at 70.02KiB/s ETA 05:34

[download] 77.4% of 101.14MiB at 159.67KiB/s ETA 02:26

[download] 77.4% of 101.14MiB at 342.15KiB/s ETA 01:08

[download] 77.4% of 101.14MiB at 486.09KiB/s ETA 00:48

[download] 77.4% of 101.14MiB at 790.26KiB/s ETA 00:29

[download] 77.5% of 101.14MiB at 1.10MiB/s ETA 00:20

[download] 77.6% of 101.14MiB at 1.66MiB/s ETA 00:13

[download] 77.9% of 101.14MiB at 2.06MiB/s ETA 00:10

[download] 78.4% of 101.14MiB at 3.12MiB/s ETA 00:07

[download] 79.4% of 101.14MiB at 2.83MiB/s ETA 00:07

[download] 81.3% of 101.14MiB at 3.49MiB/s ETA 00:05

[download] 85.3% of 101.14MiB at 4.31MiB/s ETA 00:03

[download] 86.8% of 101.14MiB at 4.81MiB/s ETA 00:02

[download] 86.8% of 101.14MiB at 71.66KiB/s ETA 03:10

[download] 86.8% of 101.14MiB at 214.98KiB/s ETA 01:03

[download] 86.8% of 101.14MiB at 501.63KiB/s ETA 00:27

[download] 86.8% of 101.14MiB at 1003.28KiB/s ETA 00:13

[download] 86.8% of 101.14MiB at 542.38KiB/s ETA 00:25

[download] 86.9% of 101.14MiB at 537.57KiB/s ETA 00:25

[download] 86.9% of 101.14MiB at 679.91KiB/s ETA 00:19

[download] 87.1% of 101.14MiB at 1.09MiB/s ETA 00:11

[download] 87.3% of 101.14MiB at 1.88MiB/s ETA 00:06

[download] 87.8% of 101.14MiB at 3.29MiB/s ETA 00:03

[download] 88.8% of 101.14MiB at 5.99MiB/s ETA 00:01

[download] 90.8% of 101.14MiB at 9.62MiB/s ETA 00:00

[download] 94.7% of 101.14MiB at 437.79KiB/s ETA 00:12

[download] 96.5% of 101.14MiB at 536.31KiB/s ETA 00:06

[download] 96.5% of 101.14MiB at 93.37KiB/s ETA 00:38

[download] 96.5% of 101.14MiB at 280.12KiB/s ETA 00:12

[download] 96.5% of 101.14MiB at 653.62KiB/s ETA 00:05

[download] 96.6% of 101.14MiB at 1.37MiB/s ETA 00:02

[download] 96.6% of 101.14MiB at 623.61KiB/s ETA 00:05

[download] 96.6% of 101.14MiB at 791.40KiB/s ETA 00:04

[download] 96.7% of 101.14MiB at 1.06MiB/s ETA 00:03

[download] 96.8% of 101.14MiB at 1.63MiB/s ETA 00:02

[download] 97.0% of 101.14MiB at 2.59MiB/s ETA 00:01

[download] 97.5% of 101.14MiB at 4.34MiB/s ETA 00:00

[download] 98.5% of 101.14MiB at 7.41MiB/s ETA 00:00

[download] 100% of 101.14MiB at 11.53MiB/s ETA 00:00

[download] 100% of 101.14MiB in 00:29

[download] Destination: C:\Users\Roikku\Downloads\ - The Roast of Nature Clicker _ Scripting for Artists [14]-(1080p60).f251.webm

[download] 0.0% of 20.21MiB at 104.94KiB/s ETA 03:17

[download] 0.0% of 20.21MiB at 314.81KiB/s ETA 01:05

[download] 0.0% of 20.21MiB at 734.55KiB/s ETA 00:28

[download] 0.1% of 20.21MiB at 1.39MiB/s ETA 00:14

[download] 0.1% of 20.21MiB at 594.89KiB/s ETA 00:34

[download] 0.3% of 20.21MiB at 798.56KiB/s ETA 00:25

[download] 0.6% of 20.21MiB at 1.06MiB/s ETA 00:18

[download] 1.2% of 20.21MiB at 1.64MiB/s ETA 00:12

[download] 2.5% of 20.21MiB at 2.61MiB/s ETA 00:07

[download] 4.9% of 20.21MiB at 4.35MiB/s ETA 00:04

[download] 9.9% of 20.21MiB at 7.47MiB/s ETA 00:02

[download] 19.8% of 20.21MiB at 12.99MiB/s ETA 00:01

[download] 39.6% of 20.21MiB at 18.57MiB/s ETA 00:00

[download] 49.0% of 20.21MiB at 17.62MiB/s ETA 00:00

[download] 49.0% of 20.21MiB at 97.16KiB/s ETA 01:48

[download] 49.0% of 20.21MiB at 291.47KiB/s ETA 00:36

[download] 49.0% of 20.21MiB at 680.09KiB/s ETA 00:15

[download] 49.1% of 20.21MiB at 1.42MiB/s ETA 00:07

[download] 49.2% of 20.21MiB at 630.20KiB/s ETA 00:16

[download] 49.3% of 20.21MiB at 716.77KiB/s ETA 00:14

[download] 49.6% of 20.21MiB at 1.04MiB/s ETA 00:09

[download] 50.2% of 20.21MiB at 1.62MiB/s ETA 00:06

[download] 51.5% of 20.21MiB at 2.59MiB/s ETA 00:03

[download] 53.9% of 20.21MiB at 4.33MiB/s ETA 00:02

[download] 58.9% of 20.21MiB at 7.41MiB/s ETA 00:01

[download] 68.8% of 20.21MiB at 12.99MiB/s ETA 00:00

[download] 88.6% of 20.21MiB at 17.54MiB/s ETA 00:00

[download] 96.5% of 20.21MiB at 16.74MiB/s ETA 00:00

[download] 96.5% of 20.21MiB at 99.69KiB/s ETA 00:07

[download] 96.5% of 20.21MiB at 299.07KiB/s ETA 00:02

[download] 96.5% of 20.21MiB at 697.82KiB/s ETA 00:01

[download] 96.5% of 20.21MiB at 1.33MiB/s ETA 00:00

[download] 96.6% of 20.21MiB at 630.35KiB/s ETA 00:01

[download] 96.8% of 20.21MiB at 795.69KiB/s ETA 00:00

[download] 97.1% of 20.21MiB at 1.05MiB/s ETA 00:00

[download] 97.7% of 20.21MiB at 1.63MiB/s ETA 00:00

[download] 98.9% of 20.21MiB at 2.63MiB/s ETA 00:00

[download] 100% of 20.21MiB at 3.18MiB/s ETA 00:00

[download] 100% of 20.21MiB in 00:01

[Merger] Merging formats into "C:\Users\Roikku\Downloads\ - The Roast of Nature Clicker _ Scripting for Artists [14]-(1080p60).mp4"

Deleting original file C:\Users\Roikku\Downloads\ - The Roast of Nature Clicker _ Scripting for Artists [14]-(1080p60).f251.webm (pass -k to keep)

Deleting original file C:\Users\Roikku\Downloads\ - The Roast of Nature Clicker _ Scripting for Artists [14]-(1080p60).f299.mp4 (pass -k to keep)

[Metadata] Adding metadata to "C:\Users\Roikku\Downloads\ - The Roast of Nature Clicker _ Scripting for Artists [14]-(1080p60).mp4"

Download finished
```

</detailes>

**Comment by Korabel47** [comment]
I can confirm this issue still persists, too, on the version 2.4.0. Custom filename was set as "%(playlist_index)s-%(title)s.%(ext)s", the output was "-<title>.\<extension>"
