### ISSUE TITLE
Error! Unhandled error (execa). // Fedora Linux

### ISSUE THREAD

**Issue by ElijahNemr** [jely2002/youtube-dl-gui#389]
**Describe the bug**
Pasting a YouTube link immediately results in an error.  

**To Reproduce**
1. Copy and paste YouTube video link into search bar
2. Press enter

**Expected behavior**
The video should begin to download

**Additional info (please complete the following information):**
 - OS: Fedora 36
 - Application version: 2.4
 - Application type: Appimage

**Comment by StefanLobbenmeier** [comment]
I think the issue is in downloading the yt-dlp binary

    ~  /opt/youtube-dl-gui/youtube-dl-gui                                                                                                                                                                                                 INT ✘  26s  
SentryError: Attempted to enable Electron native crash reporter but no DSN was supplied
    at new SentryError (/opt/youtube-dl-gui/resources/app.asar/node_modules/@sentry/electron/node_modules/@sentry/utils/dist/error.js:9:28)
    at MainBackend.<anonymous> (/opt/youtube-dl-gui/resources/app.asar/node_modules/@sentry/electron/dist/main/backend.js:152:27)
    at step (/opt/youtube-dl-gui/resources/app.asar/node_modules/tslib/tslib.js:143:27)
    at Object.next (/opt/youtube-dl-gui/resources/app.asar/node_modules/tslib/tslib.js:124:57)
    at /opt/youtube-dl-gui/resources/app.asar/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/opt/youtube-dl-gui/resources/app.asar/node_modules/tslib/tslib.js:113:16)
    at MainBackend._installNativeHandler (/opt/youtube-dl-gui/resources/app.asar/node_modules/@sentry/electron/dist/main/backend.js:146:24)
    at new MainBackend (/opt/youtube-dl-gui/resources/app.asar/node_modules/@sentry/electron/dist/main/backend.js:66:34)
    at MainClient.BaseClient (/opt/youtube-dl-gui/resources/app.asar/node_modules/@sentry/electron/node_modules/@sentry/core/dist/baseclient.js:52:25)
Sentry initialized
Checking for update
Error: Error: ENOENT: no such file or directory, open '/opt/youtube-dl-gui/resources/app-update.yml'
(node:13282) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/opt/youtube-dl-gui/resources/app-update.yml'
(node:13282) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:13282) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Checking for a new version of ffmpeg.
Current ffmpeg version: 4.4.1
ffmpeg was already up-to-date! Version: 4.4.1
Checking for a new version of yt-dlp.
Error: ENOENT: no such file or directory, open '/home/stefanl/.youtube-dl-gui/ytdlVersion'
Binaries were already up-to-date! Version: null
No tasks to restore.

**Comment by StefanLobbenmeier** [comment]
Should be fixed by #375. Until then I cherry picked the commit and made a release of this here on my fork: https://github.com/StefanLobbenmeier/youtube-dl-gui/releases/tag/untagged-2184be06e67b370f8d26. That worked on my machine (Manjaro)

**Comment by StefanLobbenmeier** [comment]
Or as another workaround you can fix this manually by downloading https://github.com/yt-dlp/yt-dlp/releases/download/2022.06.29/yt-dlp_linux and putting this in the location mentioned in your error message (~/.youtube-dl-gui/yt-dlp_linux)

**Comment by mj0123456789** [comment]
Worked on Ubuntu (22.04) Gnome.
yt-dlp (installed through sudo apt install yt-dlp) => copied from /usr/bin to ~/.youtube-dl-gui/ then renamed yt-dlp-linux (my error message showed that syntax) => OpenVideoDownloader ok when addind links now.
Great!
Thanks a lot folks. 🙏🌞

**Comment by hayguen** [comment]
Does also work on Windows' WSL Ubuntu 20.04.5 LTS.
But had to rename to `~/.youtube-dl-gui/yt-dlp-unix` as shown in the error message.

**Comment by andnorxor** [comment]
Related #401

**Comment by himyjan** [comment]
https://github.com/StefanLobbenmeier/youtube-dl-gui/releases

or

https://github.com/jely2002/youtube-dl-gui/issues/354#issuecomment-1127269708

**Comment by jely2002** [comment]
This issue has been fixed in v3 of the app, closing this issue as a result.
